### ISSUE TITLE
error on working of the algorithm

### ISSUE THREAD

**Issue by sebastienvdb** [MuhammedBuyukkinaci/Object-Classification-and-Localization-with-TensorFlow#1]
I got this error: ValueError('setting an array element with a sequence.',). Any idea how to solve this?

**Comment by MuhammedBuyukkinaci** [comment]
Hi, sorry for late response.
Could you elaborate more?

**Comment by sebastienvdb** [comment]
Hi, 
Thank you for your respond but I was able to cope with the error by using the following code for the function make_test_data():

def make_test_data():
    testing_photos = []
    for i in os.listdir():
        try: 
            print(i)
            path = os.path.join(os.getcwd(),i)
            img = cv2.imread(path,1)
            img = cv2.resize(img,(IMG_SIZE_ALEXNET,IMG_SIZE_ALEXNET))
            img = img.reshape(227, 227, 3)
            testing_photos.append(img)
            print('ok')
        except Exception as e:
            print(str(e))
    return np.array(testing_photos)

**Comment by MuhammedBuyukkinaci** [comment]
Great to hear that you coped with the problem.
