### ISSUE TITLE
Use in single-channel image 

### ISSUE THREAD

**Issue by AmericaBG** [MuhammedBuyukkinaci/Object-Classification-and-Localization-with-TensorFlow#2]
Hi! 
First, thank you very much for your input!
I would like to know if it can be applied in binary images by changing the number of channels from 3 to 1.

Thank you very much!
All the best.

**Comment by MuhammedBuyukkinaci** [comment]
Hi,
I think you can apply the same model to 2-class case. For 1 channel question, you have to [convert rgb images to grayscale](https://stackoverflow.com/questions/37203970/opencv-grayscale-mode-vs-gray-color-conversion) and change the lines of AlexNet in train.py and test.py from 

```
##CONVOLUTION LAYER 1
#Weights for layer 1
w_1 = tf.Variable(tf.truncated_normal([11,11,3,96], stddev=0.01))
#Bias for layer 1
b_1 = tf.Variable(tf.constant(0.0, shape=[[11,11,3,96][3]]))
```

to

```
##CONVOLUTION LAYER 1
#Weights for layer 1
w_1 = tf.Variable(tf.truncated_normal([11,11,1,96], stddev=0.01))
#Bias for layer 1
b_1 = tf.Variable(tf.constant(0.0, shape=[[11,11,1,96][3]]))
```
